const MANAGE_APPLICATION = {
    OPEN_ITEM: 'MANAGE_APPLICATION_OPEN_ITEM',
    OPEN_COMPONENT: 'MANAGE_APPLICATION_OPEN_COMPONENT',
    DRAWER_OPEN: 'MANAGE_APPLICATION_DRAWER_OPEN',
    COMPONENT_DRAWER_OPEN: 'MANAGE_APPLICATION_COMPONENT_DRAWER_OPEN',
    CLEAR: 'MANAGE_APPLICATION_CLEAR',
};

export {
    MANAGE_APPLICATION,
};
